'use strict';
const labels={sistema:'Sistema sob medida',automacao:'Automação de processo',ti:'TI, rede ou segurança',melhoria:'Melhoria de solução existente'};
const sample={lead:{intent:'ti',segment:'Clínica / Saúde',scale:'12 computadores',problem:'Controle de acesso e organização de arquivos em 12 computadores.',current:'Compartilhamento de arquivos diretamente entre computadores.',impact:'Risco de segurança · Retrabalho e erros',impactLevel:'Alto',urgency:'Média',location:'Jequié',contact:'Contato ainda não informado',investment:'',solution:'Diagnóstico de infraestrutura + segmentação de rede + controle de acesso + centralização/organização de arquivos + estratégia de backup.',status:'Qualificado',score:82},messages:[{role:'agent',text:'Olá! Eu sou o Agente Lacrose. Conte o problema da sua empresa.'},{role:'user',text:'Tenho uma clínica com 12 computadores e estou tendo problemas com controle de acesso e arquivos.'},{role:'agent',text:'Entendi. Como esses arquivos são organizados e compartilhados hoje?'}],updatedAt:new Date().toISOString()};
function decodeDemo(v){try{return JSON.parse(decodeURIComponent(escape(atob(v))))}catch(e){return null}}
function getData(){const q=new URLSearchParams(location.search).get('demo');if(q){const d=decodeDemo(q);if(d)return d}try{const x=JSON.parse(localStorage.getItem('lacrose_agent_demo_lead')||'null');if(x)return x}catch(e){}return sample}
const data=getData(),lead=data.lead||sample.lead;
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v||'—'}
function fill(){set('fIntent',labels[lead.intent]||lead.intent);set('fSegment',lead.segment);set('fScale',lead.scale);set('fProblem',lead.problem);set('fImpact',lead.impact);set('fUrgency',lead.urgency);set('fLocation',lead.location);set('fContact',lead.contact);set('fCurrent',lead.current);set('fInvestment',lead.investment||'Não informada / não aplicável');set('fSolution',lead.solution);set('leadStatusTop',(lead.status||'Em diagnóstico').toUpperCase());set('leadScoreTop',String(lead.score||0));set('tableNeed',labels[lead.intent]||'Diagnóstico');set('tableStatus',lead.status||'Em diagnóstico');set('tableCompany',lead.segment||'Lead recebido pelo site');set('tablePriority',lead.impactLevel==='Alto'?'Alta':lead.impactLevel==='Médio'?'Média':'Baixa');const q=document.getElementById('kpiQualified');if(q&&lead.status==='Qualificado')q.textContent='3';renderConversation()}
function renderConversation(){const box=document.getElementById('conversationList');box.innerHTML='';const msgs=data.messages||[];if(!msgs.length){box.innerHTML='<div class="empty">Nenhuma conversa foi carregada. Volte ao site, converse com o protótipo e abra o painel novamente.</div>';return}msgs.forEach(m=>{const d=document.createElement('div');d.className='conv '+(m.role==='user'?'user':'agent');const s=document.createElement('span');s.textContent=m.text;d.appendChild(s);const sm=document.createElement('small');sm.textContent=m.role==='user'?'Visitante':'Agente Lacrose';d.appendChild(sm);box.appendChild(d)})}
const titles={dashboard:'Visão geral',lead:'Oportunidade',conversation:'Conversa',audit:'Auditoria'};
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));set('pageTitle',titles[id]||'Painel')}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.viewJump)));
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
document.getElementById('approve')?.addEventListener('click',()=>{toast('Demonstração: lead marcado como aprovado para contato.');const a=document.getElementById('auditList');const row=document.createElement('div');row.innerHTML='<time>agora</time><p><b>Aprovação humana registrada</b><span>Administrador autorizou o próximo passo comercial no protótipo.</span></p><code>approval.granted</code>';a.prepend(row)});document.getElementById('request')?.addEventListener('click',()=>toast('Demonstração: solicitação de mais informações preparada, mas não enviada.'));
fill();
